<h1 align='center'> 파이썬과학프로그래밍기초 실습 7</h1>

<p style="text-align: right"> 2021.4.28.</p>

### <div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름: 장윤제  &nbsp;&nbsp;          학번: 장윤제   &nbsp;&nbsp;         학과(전공): 스마트IoT
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 과제 제출: 4월 30일 (금) 오후 6:00까지 최종본 제출. 


#### 문제 0: 아래 셀에 다음 명령을 실행하라.

```
import numpy as np
np.__version__
```


In [1]:
import numpy as np
np.__version__

'1.19.2'

#### 문제 1.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)
```

In [36]:
np.arange(8,dtype=np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)

#### 문제 2.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)
```

In [24]:
np.arange(0,15,2,dtype=np.int64)

array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)

#### 문제 3.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([1. , 1.2, 1.4, 1.6, 1.8])
```

In [23]:
np.arange(1,2,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

#### 문제 4.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### 문제 5.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 문제 6.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [20]:
np.arange(1,11,2.25)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 문제 7.
NumPy의 arange와 reshape을 사용하여 다음 ndarray를 만들어라.

```
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]], dtype=int64)
```

In [37]:
a = np.arange(2,33,2,dtype=np.int64).reshape(4,4)
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]], dtype=int64)

#### 문제 8.
문제 7에서 만든 ndarray에서 4, 12, 20, 28의 합 64를 출력하는 문장 2 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [48]:
tot = 0
for lst in a:
    tot += lst[1]
tot               #인덱싱을 이용하자!

64

In [45]:
a[:, 1].sum()

64

In [47]:
a.sum(0)[1]

64

#### 문제 9.
문제 7에서 만든 ndarray에서 18, 20, 22, 24의 합 84를 출력하는 문장 3 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [40]:
sum(a[2])

84

In [41]:
a[2, :].sum()

84

In [43]:
a.sum(1)[2]

84

#### 문제 10.
문제 7에서 만든 ndarray에서 2, 12, 22, 32의 합 68을 출력하는 문장을 작성하라.

In [56]:
a[np.arange(4),np.arange(4)]

array([ 2, 12, 22, 32], dtype=int64)

In [57]:
a[np.arange(4),np.arange(4)].sum()

68

In [52]:
sum(np.diag(a))

68

#### 문제 11.
문제 7에서 만든 ndarray에서 4, 14, 24의 합 42을 출력하는 문장을 작성하라.

In [59]:
a[np.arange(3),np.arange(1,4)]

array([ 4, 14, 24], dtype=int64)

In [62]:
a[np.arange(3),np.arange(1,4)].sum()

42

In [58]:
sum(np.diag(a,1))

42

#### 문제 12.
문제 7에서 만든 ndarray에서 10, 20, 30의 합 60을 출력하는 문장을 작성하라.

In [63]:
a[np.arange(1,4),np.arange(3)]

array([10, 20, 30], dtype=int64)

In [65]:
a[np.arange(1,4),np.arange(3)].sum()

60

In [64]:
sum(np.diag(a,-1))

60

#### 문제 15.
다음 ndarray를 만들고 변수 a에 이 객체를 할당하라. 단, 모든 원소를 직접 나열하면 안된다.

```
array([[[ 3,  6],
        [ 9, 12],
        [15, 18]],

       [[21, 24],
        [27, 30],
        [33, 36]],

       [[39, 42],
        [45, 48],
        [51, 54]],

       [[57, 60],
        [63, 66],
        [69, 72]]])
```

3차원 행렬, shape = (4,3,2)

In [66]:
a = np.arange(3,73,3).reshape(4,3,2)
a

array([[[ 3,  6],
        [ 9, 12],
        [15, 18]],

       [[21, 24],
        [27, 30],
        [33, 36]],

       [[39, 42],
        [45, 48],
        [51, 54]],

       [[57, 60],
        [63, 66],
        [69, 72]]])

#### 문제 16.
문제 15에서 만든 a에서 9, 27, 45, 63의 합 144를 출력하는 문장을 작성하라.

In [71]:
a[:,1,0].sum()

144

In [83]:
a.sum(0)[1,0]

144

In [88]:
a.sum(0)

array([[120, 132],
       [144, 156],
       [168, 180]])

#### 문제 17.
문제 15에서 만든 a와 shape과 dtype이 같고, 모든 원소가 1인 ndarray를 만들어라.

In [77]:
nda = np.ones_like(a)
print(nda)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 문제 18
문제 15에서 만든 a와 shape과 dtype이 같고, 모든 원소가 7인 ndarray를 만들어라.

In [80]:
np.ones_like(a) * 7         #broadcasting

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

In [81]:
np.full_like(a,7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])